<?php
/**
 * @file
 */

/*
 * Implements hook_menu()
 */
function bosa_iframe_menu(){
  $items = array();

  $items['bosa/iframe'] = array(
    'page callback' => 'bosa_iframe_view',
    'access arguments' => array('access content'), 
  );

  return $items;
}

/**
 * Implements hook_page_alter()
 */
function bosa_iframe_page_alter(&$page) {
  if(arg(0) == 'bosa' && arg(1) == 'iframe'){
    unset($page['page_top']);
    unset($page['footer']);
    unset($page['above-header']);
  }
}

/**
 * Implements hook_preprocess_page()
 */
function bosa_iframe_preprocess_page(&$vars, $hook) {
  if (strstr(request_uri(), 'bosa/iframe')) {
     $vars['theme_hook_suggestion'] = 'page__iframe';
  }
}

function bosa_iframe_view($type, $arg, $ids = NULL, $tid = NULL){
$script = "
  var qty = jQuery('.views-row').length;
  var width = 100;
  if(qty !== 4){
  	if(qty !== 1){
      width = 98;
  	}
    jQuery('.views-row').css('width', width+'%');
  }";

  drupal_add_js($script, array('type' => 'inline', 'scope' => 'footer', 'weight' => 5));
  switch($type){
    // Product view
    // bosa/iframe/product/<s:specified/r:random>/<optional: product node ids>
    case 'product':
      $v = views_get_view('Produktvisning_paa_kategoriside');
      switch($arg){
        case 's':
          return $v->preview('panel_pane_2', array($ids));
        
        default:
          $v->set_items_per_page($ids);
          return $v->preview('panel_pane_2', array('all', $tid));
      }
      break;

    // Category view
    // bosa/iframe/category/<number of categories>/<category ids>
    case 'category':
      $views = '';
      $ids = explode(',', $ids);
      $i = 0;
      foreach($ids as $id){
        $v = views_get_view('kategorivisning');
        $views .=  '<div class="row-' . $i . '">' . $v->preview('panel_pane_1', array($id)) . '</div>';
        $i++;
      }
      return $views;
        

    default:
      return 'Incorrect arguments';
      break;
  }
}

